### ISSUE TITLE
Monitor achtungs

### ISSUE THREAD

**Issue by amoghbl1** [00h-i-r-a00/moby_simulator#16]
We need a tool to easily monitor the usage of the achtung machines when we run a set a simulations given that it's hard to ssh into 12 machines to keep an eye on whats going on.

Figure out an easy to implement way to do this, or a tool that we can use.

Not high priority.

**Comment by amoghbl1** [comment]
Ganglia seems to be real time, can we just use that?
Need comments @00h-i-r-a00 

Ganglia: http://achtung01.ccs.neu.edu/ganglia/?r=hour&cs=&ce=&m=load_one&s=by+name&c=Achtung&tab=m&vn=&hide-hf=false

**Comment by 00h-i-r-a00** [comment]
Ganglia looks good, but lets start with what we need. The current script get_per_node_memory_consumption.py gets:

a) Number of processes of `moby_simulator.py` running on each node
b) Memory consumption by all the processes
c) Memory Availability on each node

We don't need to login for this script, only run it locally with specific parameters. It can also be extended for the `generate_messages.py` script.

At the moment, other things that I can think of:

a) Similar to Ganglia, Aggregate and Per Process Memory Consumption From Start To Finish during the entire duration of the simulation. This can also be done in `monitor_moby_simulator.sh` which already dumps memory usage every five minutes into the folder memory_logs. Or maybe use a unix utility or a cron job like you suggested with something like [this](https://devops.stackexchange.com/questions/987/how-to-get-memory-usage-per-process-with-sar-sysstat) or `vmstat` or well just any of the other memory tools.

Side-question: Does Ganglia provide the option for looking into specific processes? If yes, then maybe we can use Ganglia as well. I'll add more things over here that we need, can you do that as well? @amoghbl1 So, we can find out if we need another script or just simple modifications to the current one.

**Comment by amoghbl1** [comment]
Given that this isn't a high priority task, I don't feel it's worth working on a monitoring tool.
Ganglia doesn't give per process information AFAIK, need to look at it with more detail though.

It's really a waste of time working on this given that we have bigger fish to fry, I've opened this issue just so we have our eye on it and don't forget about it.
