### ISSUE TITLE
Get input files for rural areas

### ISSUE THREAD

**Issue by 00h-i-r-a00** [00h-i-r-a00/moby_simulator#17]
As the title suggests, we need the input files for other rural areas in Spain to have a comparison with rural vs urban in the paper.

**Comment by amoghbl1** [comment]
This is easy to do, we just need the geographical location of the rural areas after which it would be trivial.

Have you decided on which regions to use as rural areas?

**Comment by amoghbl1** [comment]
Any update on this @00h-i-r-a00 ?
