### ISSUE TITLE
Optimizing Priority Queues

### ISSUE THREAD

**Issue by 00h-i-r-a00** [00h-i-r-a00/moby_simulator#6]
Details in the branch "prioqueue" (not the recent one at the moment - will update today). Time for 10,000 messages currently stands at 34 minutes. 
TODO: Remove sorted in each message exchange to just doing it once, and see the performance optimization. 
ReferenceBranch --> [prioqueue](https://github.com/00h-i-r-a00/moby_simulator/tree/prioqueue)

**Comment by amoghbl1** [comment]
@00h-i-r-a00 Last commit on that seems to be a while ago, lemme know when you push your most recent changes!
