### ISSUE TITLE
Investigating Empty Outputs While Varying Threshold Values

### ISSUE THREAD

**Issue by 00h-i-r-a00** [00h-i-r-a00/moby_simulator#8]
Currently Some of the thresholds are returning empty files. Need to figure out 

a) why that is happening
b) which particular thresholds are causing it
c) which hours are missing
d) can these be ignored
e) get the results for all these and argue whether a decrease in performance (if we see such a thing) is due to these gaps in user connectivity 

Issues/Problems Right Now:

**1. Uncompleted Configs**
These are the configs that do not have a .nohup file with "Simulation Done!" text (text to indicate end of Simulation) i.e no logs at all are being written for them

**2. Uncompleted Configs with Partial NoHup Files**
These are configs that have .nohup files with partial output
_Solution:_ 
a) Get these simulations 
b) Re-rerun the particular simulations to see if they run okay manually.
If yes, then issue is with **run_simulations.py** and simulations are not being scheduled properly. If not, then look at the particular error.

**3. Simulations with "Simulation Done!" Message but Still Empty**
a) either message_delay or queue_occupancy files are not being written
b) both of them are not being written
Solution: Look at the .twr files and logs

**4. Account for all Errors** 
Make sure that all three of the above scenarios account for the complete set of Uncompleted Simulations, so that we don't have any error left out. 

**5. Make completely sure that 0 threshold is Causing no Error**

**Comment by amoghbl1** [comment]
Can you give me a config for which we're getting empty output?

**Comment by 00h-i-r-a00** [comment]
Update:

For **5**:
624 simulations for a threshold of zero gave results for 524 simulations. Since all of these 524 simulations yield complete results (and no empty files for example), it seems like the remaining 100 simulations were not scheduled properly. Need to look at **run_simulations.py** whether it ends up scheduling everything on the nodes (Issue 13). This error could also account for **1** in configurations with a threshold. 

@amoghbl1 Can you look at issue 13? I am about to manually check these configs, will send you one while doing that.
